/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author natalia-loeza
 */
public class FrmInicioSistema extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmInicioSistema.class.getName());

    /**
     * Creates new form InicioSistema
     */
    public FrmInicioSistema() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPasajeros = new javax.swing.JButton();
        btnCarga = new javax.swing.JButton();
        btnExpress = new javax.swing.JButton();
        btnInformacion = new javax.swing.JButton();
        lbFotoMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(null);

        btnPasajeros.setText("Pasajeros");
        getContentPane().add(btnPasajeros);
        btnPasajeros.setBounds(70, 300, 100, 30);

        btnCarga.setText("Carga");
        btnCarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCarga);
        btnCarga.setBounds(70, 360, 100, 30);

        btnExpress.setText("Express");
        btnExpress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExpressActionPerformed(evt);
            }
        });
        getContentPane().add(btnExpress);
        btnExpress.setBounds(70, 410, 100, 30);

        btnInformacion.setText("Informacion");
        getContentPane().add(btnInformacion);
        btnInformacion.setBounds(90, 510, 110, 24);

        lbFotoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/servicio.png"))); // NOI18N
        lbFotoMenu.setText("Informacion");
        getContentPane().add(lbFotoMenu);
        lbFotoMenu.setBounds(0, 0, 600, 600);
        lbFotoMenu.getAccessibleContext().setAccessibleName("lbFotoMenu");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExpressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExpressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExpressActionPerformed

    private void btnCargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCargaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmInicioSistema().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarga;
    private javax.swing.JButton btnExpress;
    private javax.swing.JButton btnInformacion;
    private javax.swing.JButton btnPasajeros;
    private javax.swing.JLabel lbFotoMenu;
    // End of variables declaration//GEN-END:variables
}
