/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
/**
 *
 * @author natalia-loeza
 */
public class FrmPeticionExpress extends javax.swing.JFrame {
    private int pisoOrigen;
    private static FrmPeticionExpress instancia;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmPeticionExpress.class.getName());

    /**
     * Creates new form FrmPeticionExpress
     */
    public FrmPeticionExpress(int pisoUsuario) {
        initComponents();
        this.pisoOrigen = pisoUsuario;
        this.setTitle("Solicitud de elevador express");
        
        int destinoAutomatico = (pisoUsuario == 1) ? 10 : 1; //calculamos el destino automaticamente
        txtPisoDestino.setText(String.valueOf(destinoAutomatico));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSolicitar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        txtPisoDestino = new javax.swing.JTextField();
        lbPeticionExpress = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 400));
        setMinimumSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(null);

        btnSolicitar.setText("Solicitar");
        btnSolicitar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSolicitarMouseClicked(evt);
            }
        });
        btnSolicitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSolicitar);
        btnSolicitar.setBounds(100, 290, 83, 24);

        btnSalir.setText("Salir");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(220, 290, 72, 24);

        txtPisoDestino.setEditable(false);
        txtPisoDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPisoDestinoActionPerformed(evt);
            }
        });
        getContentPane().add(txtPisoDestino);
        txtPisoDestino.setBounds(140, 200, 130, 20);

        lbPeticionExpress.setIcon(new javax.swing.ImageIcon(getClass().getResource("/peticionExpresss.png"))); // NOI18N
        getContentPane().add(lbPeticionExpress);
        lbPeticionExpress.setBounds(0, -22, 400, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSolicitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSolicitarActionPerformed

    private void btnSolicitarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSolicitarMouseClicked
        int pisoOrigen = this.pisoOrigen;

        int pisoDestino;
        if(pisoOrigen == 1){
            pisoDestino = 10;
        }else{
            pisoDestino = 1;
        }
    
        FrmInicioSistema.edificio.realizarPeticion(pisoOrigen, pisoDestino, 2);
        this.dispose(); //ya esta la peticion lista
    }//GEN-LAST:event_btnSolicitarMouseClicked

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnSalirMouseClicked

    private void txtPisoDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPisoDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPisoDestinoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmPeticionExpress(1).setVisible(true));
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSolicitar;
    private javax.swing.JLabel lbPeticionExpress;
    private javax.swing.JTextField txtPisoDestino;
    // End of variables declaration//GEN-END:variables
}
