/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Vista.FrmInicioSistema;
import javax.swing.JOptionPane;

/**
 *
 * @author natalia-loeza
 */
public class FrmPeticionCarga extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmPeticionCarga.class.getName());

    /**
     * Creates new form FrmPeticionCarga
     */
    public FrmPeticionCarga() {
        initComponents();
        this.setTitle("Solicitud de Carga");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbCargaPisoOrigen = new javax.swing.JComboBox<>();
        cmbCargaPisoDestino = new javax.swing.JComboBox<>();
        txtPeso = new javax.swing.JTextField();
        btnSolicitar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lbFotoPeticionCarga = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 400));
        setMinimumSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(null);

        cmbCargaPisoOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        getContentPane().add(cmbCargaPisoOrigen);
        cmbCargaPisoOrigen.setBounds(140, 160, 72, 20);

        cmbCargaPisoDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        getContentPane().add(cmbCargaPisoDestino);
        cmbCargaPisoDestino.setBounds(140, 214, 72, 20);
        getContentPane().add(txtPeso);
        txtPeso.setBounds(140, 266, 130, 24);

        btnSolicitar.setText("Solicitar");
        btnSolicitar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSolicitarMouseClicked(evt);
            }
        });
        btnSolicitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSolicitar);
        btnSolicitar.setBounds(100, 330, 100, 24);

        btnSalir.setText("Salir");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(220, 330, 83, 24);

        lbFotoPeticionCarga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/peticionCarga.png"))); // NOI18N
        getContentPane().add(lbFotoPeticionCarga);
        lbFotoPeticionCarga.setBounds(0, 0, 400, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSolicitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSolicitarActionPerformed

    private void btnSolicitarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSolicitarMouseClicked
        try {
            String origenStr = cmbCargaPisoOrigen.getSelectedItem().toString();
            String destinoStr = cmbCargaPisoDestino.getSelectedItem().toString();
            
            int pisoOrigen = Integer.parseInt(origenStr);
            int pisoDestino = Integer.parseInt(destinoStr);

            if(pisoOrigen == pisoDestino){
                JOptionPane.showMessageDialog(this, "El origen y destino son iguales.", "Error", JOptionPane.WARNING_MESSAGE);
                return;
            }

            if(txtPeso.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Por favor ingrese el peso de la carga.");
                return;
            }

            double pesoIngresado = Double.parseDouble(txtPeso.getText());

            if(pesoIngresado <= 0){
                JOptionPane.showMessageDialog(this, "El peso debe ser mayor a 0.");
                return;
            }

            if(pesoIngresado > 200){
                // alarma de sobrepeso
                JOptionPane.showMessageDialog(this, 
                        "Sobrecarga en el elevador\n" +
                        "Peso ingresado: " + pesoIngresado + "kg\n" +
                        "Límite permitido: 200" + "kg\n\n" +
                        "El elevador no se moverá hasta reducir la carga.", 
                        "Error de Peso", 
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
            //si esta todo bien continuamos
            FrmInicioSistema.edificio.realizarPeticion(pisoOrigen, pisoDestino, 3);
            
            JOptionPane.showMessageDialog(this, "Carga aceptada. Elevador solicitado.");
            this.dispose(); // cerramos la ventana

        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "El peso debe ser un número válido (ej. 50.5).");
        }
    }//GEN-LAST:event_btnSolicitarMouseClicked

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnSalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmPeticionCarga().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSolicitar;
    private javax.swing.JComboBox<String> cmbCargaPisoDestino;
    private javax.swing.JComboBox<String> cmbCargaPisoOrigen;
    private javax.swing.JLabel lbFotoPeticionCarga;
    private javax.swing.JTextField txtPeso;
    // End of variables declaration//GEN-END:variables
}
