/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JOptionPane;

/**
 *
 * @author natalia-loeza
 */
public class FrmPeticionPasajeros extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmPeticionPasajeros.class.getName());

    /**
     * Creates new form FrmPeticionPasajeros
     */
    public FrmPeticionPasajeros() {
        initComponents();
        this.setTitle("Solicitud de Pasajeros");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbPisoOrigen = new javax.swing.JComboBox<>();
        cmbPisoDestino = new javax.swing.JComboBox<>();
        btnSolicitar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lbFotoPeticionPasajeros = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 400));
        setMinimumSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(null);

        cmbPisoOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        getContentPane().add(cmbPisoOrigen);
        cmbPisoOrigen.setBounds(140, 160, 72, 20);

        cmbPisoDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        getContentPane().add(cmbPisoDestino);
        cmbPisoDestino.setBounds(140, 240, 72, 20);

        btnSolicitar.setText("Solicitar");
        btnSolicitar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSolicitarMouseClicked(evt);
            }
        });
        getContentPane().add(btnSolicitar);
        btnSolicitar.setBounds(90, 330, 83, 24);

        btnSalir.setText("Salir");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(200, 330, 72, 24);

        lbFotoPeticionPasajeros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/peticionPasajeros.png"))); // NOI18N
        getContentPane().add(lbFotoPeticionPasajeros);
        lbFotoPeticionPasajeros.setBounds(0, 0, 420, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSolicitarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSolicitarMouseClicked
        try {
            String origen = cmbPisoOrigen.getSelectedItem().toString();
            String destino = cmbPisoDestino.getSelectedItem().toString();
            
            int pisoOrigen = Integer.parseInt(origen);
            int pisoDestino = Integer.parseInt(destino);
            
            if (pisoOrigen == pisoDestino) {
                JOptionPane.showMessageDialog(this, 
                        "El piso de origen y destino son iguales.\n" +
                        "Ya estás en ese piso", 
                        "Error Lógico", 
                        JOptionPane.WARNING_MESSAGE);
                return; 
            }
            
            FrmInicioSistema.edificio.realizarPeticion(pisoOrigen, pisoDestino, 1);

            JOptionPane.showMessageDialog(this, 
                    "Solicitud enviada.\nTu elevador va en camino.", 
                    "Éxito", 
                    JOptionPane.INFORMATION_MESSAGE);
            
            this.dispose();

        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Ocurrió un error al procesar la solicitud.");
        }
    }//GEN-LAST:event_btnSolicitarMouseClicked

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnSalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmPeticionPasajeros().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSolicitar;
    private javax.swing.JComboBox<String> cmbPisoDestino;
    private javax.swing.JComboBox<String> cmbPisoOrigen;
    private javax.swing.JLabel lbFotoPeticionPasajeros;
    // End of variables declaration//GEN-END:variables
}
